/**
 * How the two generated `.gs` files are serialised.
 *
 * Kept apart from the scripts that write them so a test can re-render and
 * compare without running a generator for its side effects:
 * `frontend/repoHygiene.test.ts` renders `SearchAliases.gs` from the JSON and
 * fails when the committed file has drifted.
 *
 * Everything here is a pure string function, and the alias output carries no
 * timestamp — a byte-for-byte comparison is only possible if re-rendering the
 * same input always produces the same bytes.
 */

/** Max line length of the emitted tables; `backend/Config.gs` reads at ~95. */
const WIDTH = 96;

export interface AliasSpec {
  /**
   * Query → MOA root name. Keys are the FOLDED form `normalizeQuery` produces
   * (trimmed, half-width, lower-cased), so a lookup is one map hit on both ends.
   */
  aliases: Record<string, string>;
  /** Simplified → traditional, produce vocabulary only. */
  simplified: Record<string, string>;
  /** Question suffixes a query may end with, stripped longest-first. */
  suffixes: string[];
}

/**
 * A `.gs` string literal. Apps Script is ES5 here and the tables are plain
 * data, so anything needing an escape is a mistake in the source JSON rather
 * than something to encode around — it throws instead.
 */
function literal(value: string): string {
  if (/['\\\n]/.test(value)) throw new Error(`unquotable value in the alias table: ${JSON.stringify(value)}`);
  return `'${value}'`;
}

/** Greedily packs tokens into indented lines, so a table stays diff-readable. */
function wrap(tokens: string[], indent = '  '): string[] {
  const lines: string[] = [];
  let line = '';
  for (const token of tokens) {
    const candidate = line ? `${line} ${token}` : indent + token;
    if (line && candidate.length > WIDTH) {
      lines.push(line);
      line = indent + token;
    } else {
      line = candidate;
    }
  }
  if (line) lines.push(line);
  return lines;
}

function mapBody(table: Record<string, string>): string[] {
  const entries = Object.keys(table);
  return wrap(entries.map((key, i) => `${literal(key)}: ${literal(table[key])}${i === entries.length - 1 ? '' : ','}`));
}

/** `backend/SearchAliases.gs` — the shared JSON as Apps Script globals. */
export function renderSearchAliases(spec: AliasSpec): string {
  for (const key of Object.keys(spec.aliases)) {
    // A key that is not already folded could never be hit: `normalizeQuery`
    // lower-cases and half-widths a query before looking it up.
    if (key !== key.toLowerCase() || /[\uFF01-\uFF5E\u3000]/.test(key)) {
      throw new Error(`alias key is not folded (lower-case, half-width): ${key}`);
    }
  }

  return [
    '// GENERATED from shared/search-aliases.json — run `npm run sync-aliases` in tools/catalog.',
    '// Edit the JSON, never this file: the frontend imports the same JSON, and',
    '// frontend/repoHygiene.test.ts fails when the two drift apart.',
    '',
    '',
    '/**',
    ' * Search aliases → MOA root name (Chinese; the API only accepts Chinese).',
    ' * Covers common English and colloquial terms plus the many cases where the',
    ' * everyday name is not the MOA root name. Keys are already folded, so',
    ' * `normalizeQuery` can look one up directly.',
    ' */',
    'var SEARCH_ALIASES = {',
    ...mapBody(spec.aliases),
    '};',
    '',
    '/**',
    ' * Simplified → traditional, produce vocabulary only — no OpenCC, no full',
    ' * conversion table. Every key exists only in simplified Chinese, so the map',
    ' * cannot rewrite a query that was already Traditional.',
    ' */',
    'var SIMPLIFIED_TO_TRADITIONAL = {',
    ...mapBody(spec.simplified),
    '};',
    '',
    '/** Question suffixes 「高麗菜多少錢」 carries; stripped longest-first. */',
    'var QUERY_SUFFIXES = [',
    ...wrap(spec.suffixes.map((s, i) => `${literal(s)}${i === spec.suffixes.length - 1 ? '' : ','}`)),
    '];',
    '',
  ].join('\n');
}

/** `backend/CropCatalog.gs` — the crawled root names plus a provenance line. */
export function renderCropCatalog(roots: string[], meta: { date: string; months: number }): string {
  return [
    '// GENERATED by tools/catalog (`npm run build-catalog`) on ' + meta.date + ', ' + roots.length +
      ' roots, roots unseen for ' + meta.months + ' months dropped.',
    '// Do not edit by hand; re-run the crawl instead (README §7).',
    '',
    '',
    '/**',
    ' * Every MOA root crop name that really traded recently.',
    ' *',
    ' * This is the search gate: a query matching no root here cannot exist in the',
    ' * feed, so `handleSearch` answers it immediately instead of probing trading',
    ' * dates and running two live queries for nothing.',
    ' */',
    'var CROP_CATALOG = [',
    ...wrap(roots.map((root, i) => `${literal(root)}${i === roots.length - 1 ? '' : ','}`)),
    '];',
    '',
  ].join('\n');
}
