import { render, screen, fireEvent } from '@testing-library/react';
import { describe, it, expect, beforeEach, vi } from 'vitest';
import UpdatePrompt from './UpdatePrompt';

// The real module is generated by vite-plugin-pwa and would register a worker;
// this stands in for it so the two states can be driven from a test.
const pwa = vi.hoisted(() => ({
  needRefresh: false,
  setNeedRefresh: vi.fn(),
  updateServiceWorker: vi.fn(),
}));

vi.mock('virtual:pwa-register/react', () => ({
  useRegisterSW: () => ({
    needRefresh: [pwa.needRefresh, pwa.setNeedRefresh],
    offlineReady: [false, vi.fn()],
    updateServiceWorker: pwa.updateServiceWorker,
  }),
}));

describe('UpdatePrompt', () => {
  beforeEach(() => {
    pwa.needRefresh = false;
    pwa.setNeedRefresh.mockClear();
    pwa.updateServiceWorker.mockClear();
  });

  it('stays out of the way while no update is waiting', () => {
    const { container } = render(<UpdatePrompt />);
    expect(container).toBeEmptyDOMElement();
  });

  it('offers the new version once a worker is waiting', () => {
    pwa.needRefresh = true;
    render(<UpdatePrompt />);
    expect(screen.getByText('已更新，重新整理看新版')).toBeInTheDocument();
    expect(screen.getByRole('button', { name: '重新整理' })).toBeInTheDocument();
    expect(screen.getByRole('button', { name: '稍後' })).toBeInTheDocument();
  });

  it('never takes the update on its own', () => {
    pwa.needRefresh = true;
    render(<UpdatePrompt />);
    // The whole point of `registerType: 'prompt'`: rendering the line must not
    // activate the waiting worker, which is what reloads the page.
    expect(pwa.updateServiceWorker).not.toHaveBeenCalled();
  });

  it('activates the waiting worker when asked to', () => {
    pwa.needRefresh = true;
    render(<UpdatePrompt />);
    fireEvent.click(screen.getByRole('button', { name: '重新整理' }));
    expect(pwa.updateServiceWorker).toHaveBeenCalledWith(true);
  });

  it('dismisses the line without activating the worker', () => {
    pwa.needRefresh = true;
    render(<UpdatePrompt />);
    fireEvent.click(screen.getByRole('button', { name: '稍後' }));
    expect(pwa.setNeedRefresh).toHaveBeenCalledWith(false);
    expect(pwa.updateServiceWorker).not.toHaveBeenCalled();
  });
});
