// GENERATED by tools/calibrate on 2026-10-01 from data through 2026-09. Do not edit by hand.
//
// Estimated traditional-market retail markup in 元/台斤, ADDED to the
// wholesale catty price. Three tiers, most specific first; `retailBand` in
// Aggregate.gs picks between them and rounds the result outward to NT$5.
//
// The model, the tiers and the rules that decide what is listed are
// documented in README §4. This month's fit, its held-out accuracy and the
// per-crop observation counts are in tools/calibrate/report/2026-09.md.
//
// Values are this run's fit.

/** Tier 1: fitted midpoint markup; the band is a fixed multiple of it. */
var RETAIL_MARKUP_ROOT = {
  '包心白菜': 19, '大蒜': 75, '小番茄': 75, '木瓜': 27, '柚子': 51, '柿子': 40,
  '桶柑': 33, '梨': 26, '棗子': 53, '椪柑': 33, '洋蔥': 17, '海梨柑': 36,
  '甘藍': 29, '甜橙': 8, '番石榴': 22, '紅龍果': 36, '絲瓜': 30, '胡瓜': 31,
  '胡蘿蔔': 19, '芒果': 44, '花椰菜': 40, '花胡瓜': 20, '茂谷柑': 44, '荔枝': 15,
  '蓮霧': 73, '蕹菜': 17, '蘿蔔': 23, '西瓜': 21, '雜柑': 10, '青江白菜': 35,
  '青蔥': 57, '香蕉': 23, '鳳梨': 17
};

/** Tier 2: fitted [p10, median, p90] of the crop's own markup distribution. */
var RETAIL_BAND_ROOT = {
  '冬瓜': [25, 28, 30], '小白菜': [21, 33, 36], '扁蒲': [32, 38, 44], '濕木耳': [61, 66, 82],
  '濕香菇': [59, 76, 83], '牛蒡': [26, 36, 40], '玉米': [49, 59, 73], '甜椒': [61, 69, 83],
  '甜瓜': [97, 114, 122], '番茄': [52, 59, 75], '芋': [46, 49, 52], '芥菜': [39, 50, 68],
  '苦瓜': [51, 57, 69], '茄子': [48, 56, 68], '茭白筍': [104, 110, 126], '莧菜': [21, 29, 36],
  '菜豆': [73, 86, 99], '萵苣菜': [35, 40, 51], '葡萄': [86, 100, 122], '薑': [57, 64, 74],
  '豌豆': [77, 94, 106], '釋迦': [43, 66, 74], '韭菜': [34, 42, 54], '馬鈴薯': [28, 30, 32]
};

/** Tier 3: hand-tuned per-category [low, mid, high] fallback. Not fitted. */
var RETAIL_MARKUP_CATEGORY = {
  '葉菜類': [20, 35, 50],
  '根莖類': [19, 28, 48],
  '果菜類': [48, 70, 88],
  '瓜果類': [22, 32, 50],
  '辛香類': [45, 55, 80],
  '菇類': [40, 60, 85],
  '水果': [17, 32, 62],
  '其他': [20, 35, 50]
};
