// GENERATED by tools/calibrate on 2026-09-07 from data through 2026-09. Do not edit by hand.
//
// Estimated traditional-market retail markup in 元/台斤, ADDED to the
// wholesale catty price. Three tiers, most specific first; `retailBand` in
// Aggregate.gs picks between them and rounds the result outward to NT$5.
//
// The model, the tiers and the rules that decide what is listed are
// documented in README §4. This month's fit, its held-out accuracy and the
// per-crop observation counts are in tools/calibrate/report/2026-09.md.
//
// Values carried over unchanged: this run's refit is reported as a proposal,
// not adopted. See the report for the old-vs-new comparison.

/** Tier 1: fitted midpoint markup; the band is a fixed multiple of it. */
var RETAIL_MARKUP_ROOT = {
  '包心白菜': 24, '大蒜': 68, '小番茄': 59, '木瓜': 29, '柚子': 49, '柿子': 57,
  '桶柑': 31, '梨': 36, '棗子': 49, '椪柑': 34, '洋蔥': 18, '甘藍': 29,
  '番石榴': 20, '紅龍果': 38, '絲瓜': 27, '胡瓜': 28, '胡蘿蔔': 18, '芒果': 33,
  '花椰菜': 36, '花胡瓜': 22, '茂谷柑': 50, '荔枝': 22, '蓮霧': 52, '蕹菜': 21,
  '蘿蔔': 20, '西瓜': 18, '青江白菜': 33, '青蔥': 51, '香蕉': 14, '鳳梨': 13
};

/** Tier 2: fitted [p10, median, p90] of the crop's own markup distribution. */
var RETAIL_BAND_ROOT = {
  '冬瓜': [26, 28, 32], '小白菜': [20, 32, 36], '扁蒲': [32, 38, 43], '敏豆': [78, 87, 112],
  '楊桃': [17, 29, 57], '濕木耳': [61, 66, 81], '牛蒡': [32, 36, 40], '甜椒': [56, 64, 70],
  '甜瓜': [94, 119, 121], '番茄': [53, 59, 68], '芋': [47, 48, 51], '芥菜': [39, 48, 54],
  '芥藍菜': [48, 52, 66], '苦瓜': [49, 56, 65], '茄子': [48, 56, 60], '茭白筍': [109, 118, 126],
  '茼蒿': [37, 51, 60], '莧菜': [18, 30, 34], '薑': [61, 65, 79], '韭菜': [41, 43, 57],
  '馬鈴薯': [28, 31, 32]
};

/** Tier 3: hand-tuned per-category [low, mid, high] fallback. Not fitted. */
var RETAIL_MARKUP_CATEGORY = {
  '葉菜類': [20, 35, 50],
  '根莖類': [19, 28, 48],
  '果菜類': [48, 70, 88],
  '瓜果類': [22, 32, 50],
  '辛香類': [45, 55, 80],
  '菇類': [40, 60, 85],
  '水果': [17, 32, 62],
  '其他': [20, 35, 50]
};
