/**
 * The generated `.gs` file is Apps Script source, so these tests hold it to the
 * same invariants `frontend/backendCode.test.ts` holds the hand-written files
 * to: three `var`s, no cross-file initialiser, and values a parser agrees with.
 *
 * `renderGs` is exercised rather than `emit` — a test run must not overwrite the
 * backend file it is checking.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { renderGs, fittedTables, compareWithShipped, changeList, GENERATED_GS } from '../src/emit.ts';
import type { ShippedTables } from '../src/emit.ts';
import { RETAIL_MARKUP_CATEGORY } from '../src/category-bands.ts';
import type { CropFit } from '../src/fit.ts';
import { loadBackend } from '../src/backend.ts';

const options = { keepShipped: false, generatedOn: '2026-09-06', dataThrough: '2026-09' };

const fit = (over: Partial<CropFit>): CropFit => ({
  root: 'x', category: '葉菜類', tier: 'tier1', listed: true, reason: 'test',
  counts: { taichung: 30, taipei: 0, total: 30 },
  categoryBand: RETAIL_MARKUP_CATEGORY['葉菜類'], ...over,
});

const tables: ShippedTables = {
  markupRoot: { '甘藍': 29, '包心白菜': 24 },
  bandRoot: { '番茄': [53, 59, 68], '冬瓜': [26, 28, 32] },
};

/** Evaluates the rendered source the way Apps Script would: one shared scope. */
function evaluateGs(source: string) {
  return new Function(`${source}\nreturn { RETAIL_MARKUP_ROOT, RETAIL_BAND_ROOT, RETAIL_MARKUP_CATEGORY };`)();
}

describe('the generated Apps Script file', () => {
  const source = renderGs(tables, options);

  it('says what generated it, when, and how far the data reaches', () => {
    expect(source.split('\n')[0]).toBe(
      '// GENERATED by tools/calibrate on 2026-09-06 from data through 2026-09. Do not edit by hand.',
    );
    expect(source).toContain('tools/calibrate/report/2026-09.md');
    expect(source).toContain('README §4');
  });

  it('declares exactly the three tables, once each', () => {
    const declarations = [...source.matchAll(/^(?:function (\w+)|var (\w+))/gm)].map((m) => m[1] ?? m[2]);
    expect(declarations).toEqual(['RETAIL_MARKUP_ROOT', 'RETAIL_BAND_ROOT', 'RETAIL_MARKUP_CATEGORY']);
  });

  it('parses back to the tables it was given', () => {
    const parsed = evaluateGs(source);
    expect(parsed.RETAIL_MARKUP_ROOT).toEqual(tables.markupRoot);
    expect(parsed.RETAIL_BAND_ROOT).toEqual({ '番茄': [53, 59, 68], '冬瓜': [26, 28, 32] });
    expect(parsed.RETAIL_MARKUP_CATEGORY).toEqual(RETAIL_MARKUP_CATEGORY);
  });

  it('copies the hand-tuned category table through unchanged', () => {
    // The category bands are an input the tool never fits. A refit that moved
    // them would silently change every crop on the fallback tier.
    expect(evaluateGs(source).RETAIL_MARKUP_CATEGORY).toEqual(RETAIL_MARKUP_CATEGORY);
    expect(evaluateGs(renderGs({ markupRoot: {}, bandRoot: {} }, options)).RETAIL_MARKUP_CATEGORY)
      .toEqual(RETAIL_MARKUP_CATEGORY);
  });

  it('orders keys deterministically, so a no-change refit is an empty diff', () => {
    const shuffled: ShippedTables = {
      markupRoot: { '包心白菜': 24, '甘藍': 29 },
      bandRoot: { '冬瓜': [26, 28, 32], '番茄': [53, 59, 68] },
    };
    expect(renderGs(shuffled, options)).toBe(source);
  });

  it('has no initialiser that reads another file — load order must stay irrelevant', () => {
    // Mirrors the assertion in frontend/backendCode.test.ts: a `var` whose
    // value comes from a call or another constant would make Apps Script's
    // file order load-bearing.
    for (const line of source.split('\n')) {
      const declaration = line.match(/^var \w+ = (.*)$/);
      if (!declaration) continue;
      expect(declaration[1]).toBe('{');
    }
  });

  it('names --keep-shipped in the header when the fit was not adopted', () => {
    expect(renderGs(tables, { ...options, keepShipped: true })).toContain('carried over unchanged');
    expect(source).not.toContain('carried over unchanged');
  });

  it('is what the repo actually ships', () => {
    // The committed file must be this renderer's output, or someone edited it
    // by hand and the next refit will produce a bewildering diff.
    const committed = readFileSync(GENERATED_GS, 'utf8');
    const parsed = evaluateGs(committed);
    expect(committed).toBe(renderGs(
      { markupRoot: parsed.RETAIL_MARKUP_ROOT, bandRoot: parsed.RETAIL_BAND_ROOT },
      {
        keepShipped: committed.includes('carried over unchanged'),
        generatedOn: committed.match(/on (\d{4}-\d{2}-\d{2})/)![1],
        dataThrough: committed.match(/data through (\d{4}-\d{2})/)![1],
      },
    ));
  });
});

describe('the old-vs-new comparison', () => {
  const fits: CropFit[] = [
    fit({ root: '甘藍', markup: 30 }),
    fit({ root: '包心白菜', markup: 24 }),
    fit({ root: '番茄', tier: 'tier2', band: [54, 60, 67], category: '果菜類', counts: { taichung: 0, taipei: 18, total: 18 } }),
    fit({ root: '冬瓜', tier: 'tier2', band: [26, 28, 32], category: '瓜果類', counts: { taichung: 0, taipei: 18, total: 18 } }),
    fit({ root: '莧菜', tier: 'tier2', band: [18, 30, 34], counts: { taichung: 0, taipei: 18, total: 18 } }),
    fit({ root: '龍眼', tier: 'category', listed: false, category: '水果', counts: { taichung: 0, taipei: 5, total: 5 } }),
  ];

  it('collects only the crops that end up listed', () => {
    const fitted = fittedTables(fits);
    expect(Object.keys(fitted.markupRoot).sort()).toEqual(['包心白菜', '甘藍']);
    expect(Object.keys(fitted.bandRoot).sort()).toEqual(['冬瓜', '番茄', '莧菜']);
  });

  it('measures the tier-2 medians against what shipped and gates on 17 of them', () => {
    const reproduction = compareWithShipped(fits, tables);
    expect(reproduction.tier1.common).toBe(2);
    expect(reproduction.tier1.medianAbsDelta).toBe(0.5); // |30−29| and |24−24|
    expect(reproduction.tier1.offBy5).toEqual([]);
    expect(reproduction.tier2.common).toBe(2);
    expect(reproduction.tier2.within2).toBe(2);
    expect(reproduction.tier2.added).toEqual(['莧菜']);
    // Two crops within NT$2 is not 17: a partial refit must never claim to
    // reproduce the shipped table.
    expect(reproduction.gate).toBe(false);
  });

  it('flags a tier-1 crop that moved by more than NT$5', () => {
    const moved = compareWithShipped([fit({ root: '甘藍', markup: 44 })], tables);
    expect(moved.tier1.offBy5).toEqual(['甘藍']);
    expect(moved.tier1.dropped).toEqual(['包心白菜']);
  });

  it('ranks changes by the NT$ a card would move, category fallback included', () => {
    const changes = changeList(fits, tables);
    const amaranth = changes.find((c) => c.root === '莧菜');
    // Newly listed at 30 against the 葉菜類 mid of 35 it used to fall back to.
    expect(amaranth?.before).toBe(RETAIL_MARKUP_CATEGORY['葉菜類'][1]);
    expect(amaranth?.after).toBe(30);
    expect(amaranth?.note).toBe('newly listed');
    expect(changes.map((c) => c.delta)).toEqual([...changes.map((c) => c.delta)].sort((a, b) => b - a));
  });

  it('reads the shipped tables out of the backend rather than a second copy', () => {
    const backend = loadBackend();
    expect(Object.keys(backend.RETAIL_MARKUP_ROOT).length).toBeGreaterThan(0);
    expect(Object.keys(backend.RETAIL_BAND_ROOT).length).toBeGreaterThan(0);
  });
});
