/// <reference types="vite/client" />
// `virtual:pwa-register/react` is generated by vite-plugin-pwa at build time;
// this is the only way TypeScript learns that the module exists.
/// <reference types="vite-plugin-pwa/react" />
